apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-vol
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-claim
