apiVersion: v1
kind: Pod
metadata:
  name: simple-http
  labels:
    name: simple-http
spec:
  containers:
  - name: simple-http-pod
    image: zreigz/simple-http-pod
    ports:
    - containerPort: 8080
